sudo: false
dist: xenial
language: python

python:
  - "3.7"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.rf_cache

scala:
  - 2.11.11

env:
  - COURSIER_VERBOSITY=-1 JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - pandoc

install:
  - pip install rasterio shapely pandas numpy
  - wget -O - https://piccolo.link/sbt-1.2.8.tgz | tar xzf -

script:
  - sbt/bin/sbt -java-home $JAVA_HOME -batch test
  - sbt/bin/sbt -java-home $JAVA_HOME -batch it:test
  #  - sbt -Dfile.encoding=UTF8 clean coverage test coverageReport
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

