sudo: false

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.rf_cache

scala:
  - 2.11.11

jdk:
  - daunnc/openjdk-gdal:2.4.0

addons:
  apt:
    packages:
      - pandoc
      - python-pip

install:
  - pip install setuptools

sbt_args: -no-colors

script:
  - sbt test
  - sbt it:test
  #  - sbt -Dfile.encoding=UTF8 clean coverage test coverageReport
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

#after_success:
#  - bash <(curl -s https://codecov.io/bash)