dist: xenial
language: python

python:
  - "3.7"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.rf_cache
    - $HOME/.cache/coursier

scala:
  - 2.11.11

env:
  - COURSIER_VERBOSITY=-1 JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - pandoc

install:
  - pip install rasterio shapely pandas numpy pweave
  - wget -O - https://piccolo.link/sbt-1.2.8.tgz | tar xzf -


jobs:
  include:
    - stage: "Unit Tests"
      script: sbt/bin/sbt -java-home $JAVA_HOME -batch test
    - stage: "Integration"
      script: sbt/bin/sbt -java-home $JAVA_HOME -batch it:test
