sudo: false

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

scala:
  - 2.11.11

jdk:
  - oraclejdk8

addons:
  apt_packages:
    - pandoc

sbt_args: -no-colors

script:
  - sbt -Dfile.encoding=UTF8 clean test it:test
  #  - sbt -Dfile.encoding=UTF8 clean coverage test coverageReport
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
